# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EjercicioFinal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EjercicioFinal
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'lottie-ios'

end
